### ISSUE TITLE
intelstack - HTTP Error 402: Payment Required' ???

### ISSUE THREAD

**Issue by nand0san** [juju4/ansible-bro-ids#2]
This is not really an issue, but...

Ho do you avoid HTTP Error 402: Payment Required' ??? for intelstack installation??????

Thank you for sharing your work!

**Comment by juju4** [comment]
Sorry but I don't know.
I only took a quick look recently and I'm not sure if access is still free or not as company seems to have been acquired.

If you find, please share.

**Comment by juju4** [comment]
Closing old issue
